[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=65.6.3",
    "wheel>=0.38.4",
]

[project]
name = "serverless-sdk"
version = "0.1.4"
description = "Serverless SDK for Python"
readme = "README.md"
authors = [{ name = "serverlessinc" }]
requires-python = ">=3.7"
dependencies = [
    "backports.cached-property", # included in Python >=3.8
    "importlib_metadata>=5.2", # included in Python >=3.8
    "js-regex<1.1.0,>=1.0.1",
    "pydantic>=1.10.4",
    "pyhumps>=3.8",
    "typing-extensions>=4.4", # included in Python 3.8 - 3.11
]
[project.optional-dependencies]
tests = [
    "black>=22.12",
    "pytest>=7.2",
    "ruff>=0.0.199",
]
[project.urls]
changelog = "https://github.com/serverless/console/blob/main/python/packages/sdk/CHANGELOG.md"
documentation = "https://github.com/serverless/console/tree/main/python/packages/sdk"
homepage = "https://www.serverless.com/console"
repository = "https://github.com/serverless/console"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff]
ignore = ["F401"]
#fix = true
