[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=65.6.3",
    "wheel>=0.38.4",
]

[project]
name = "serverless-aws-lambda-sdk"
version = "0.1.13"
description = "Serverless AWS Lambda SDK for Python"
readme = "README.md"
authors = [{ name = "serverlessinc" }]
requires-python = ">=3.7"
dependencies = [
    "aiohttp~=3.8",
    "serverless-sdk~=0.3.12",
    "serverless-sdk-schema~=0.2.1",
    "typing-extensions~=4.5", # included in Python 3.8 - 3.11
]
[project.optional-dependencies]
tests = [
    "black>=22.12",
    "pytest>=7.2",
    "pytest-aiohttp>=1.0.4",
    "pytest-httpserver>=1.0.6",
    "requests_mock>=1.10",
    "ruff>=0.0.199",
    "serverless-wsgi>=3.0.2",
]
[project.urls]
changelog = "https://github.com/serverless/console/blob/main/python/packages/aws-lambda-sdk/CHANGELOG.md"
documentation = "https://github.com/serverless/console/tree/main/python/packages/aws-lambda-sdk"
homepage = "https://www.serverless.com/console"
repository = "https://github.com/serverless/console"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff]
ignore = ["F401", "E722"]
exclude = ["syntax_error.py", "tests/fixtures/lambdas"]
