[build-system]
build-backend = "setuptools.build_meta"
requires = [
    "setuptools>=65.6.3",
    "wheel>=0.38.4",
]

[project]
name = "serverless-aws-lambda-sdk"
description = "Serverless AWS Lambda SDK for Python"
readme = "README.md"
authors = [{ name = "serverlessinc" }]
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dynamic = [
    "version",
]
dependencies = [
    "serverless-sdk~=0.4.5",
    "serverless-sdk-schema~=0.2.1",
    "typing-extensions~=4.5", # included in Python 3.8 - 3.11
    "wrapt~=1.15.0",
    "yarl~=1.8.0",
]
[project.optional-dependencies]
tests = [
    "black>=22.12",
    "boto3>=1.16.112",
    "flask>=2.2.3",
    "importlib_metadata>=5.2", # included in Python >=3.8
    "moto>=4.1.7",
    "pynamodb>=5.5",
    "pytest>=7.2",
    "pytest-aiohttp>=1.0.4",
    "pytest-httpserver>=1.0.6",
    "requests_mock>=1.10",
    "ruff>=0.0.199",
    "serverless-wsgi>=3.0.2",
]
[project.urls]
changelog = "https://github.com/serverless/console/blob/main/python/packages/aws-lambda-sdk/CHANGELOG.md"
documentation = "https://github.com/serverless/console/tree/main/python/packages/aws-lambda-sdk"
homepage = "https://www.serverless.com/console"
repository = "https://github.com/serverless/console"

[tool.setuptools.package-data]
"*" = ["VERSION"]

[tool.setuptools.dynamic]
version = {file = "./serverless_aws_lambda_sdk/VERSION"}

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff]
ignore = ["F401", "E722"]
exclude = ["tests"]
