# PR's only

name: Integrate

on:
  push:
    branches: [main]

env:
  FORCE_COLOR: 1

jobs:
  linuxNode16:
    name: '[Linux] Node.js v16: Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve ~/.npm from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**package*.json') }}
          restore-keys: npm-v16-${{ runner.os }}-${{ github.ref }}-

      - name: Retrieve node_modules from cache
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: node-modules-v16-${{ runner.os }}-${{ github.ref }}-

      - name: Retrieve packages/aws-lambda-otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/package.json') }}
          restore-keys: packages/aws-lambda-otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-
      - name: Retrieve packages/aws-lambda-otel-extension/opt/otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/opt/otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/opt/otel-extension/package.json') }}
          restore-keys: packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-
      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install main project dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: |
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension
          npm update --no-save
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension/opt/otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension/opt/otel-extension
          npm update --no-save

      - name: Unit tests
        run: |
          cd packages/aws-lambda-otel-extension
          npm test

  linuxNode14:
    name: '[Linux] Node.js v14: Isolated Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve ~/.npm from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**package*.json') }}
          restore-keys: npm-v14-${{ runner.os }}-${{ github.ref }}-

      - name: Retrieve node_modules from cache
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
          restore-keys: node-modules-v14-${{ runner.os }}-${{ github.ref }}-
      - name: Retrieve packages/aws-lambda-otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/node-modules-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/package.json') }}
          restore-keys: packages/aws-lambda-otel-extension/node-modules-v14-${{ runner.os }}-${{ github.ref }}-
      - name: Retrieve packages/aws-lambda-otel-extension/opt/otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/opt/otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v14-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/opt/otel-extension/package.json') }}
          restore-keys: packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v14-${{ runner.os }}-${{ github.ref }}-

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install main project dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: |
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension
          npm update --no-save
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension/opt/otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd packages/aws-lambda-otel-extension/opt/otel-extension
          npm update --no-save

      - name: Unit tests
        run: |
          # npm v6 doesn't add parent node_modules/.bin to PATH, workaround it
          export PATH="$PWD/node_modules/.bin:$PATH"
          cd packages/aws-lambda-otel-extension
          npm run test:isolated

  integrate:
    name: Integrate
    runs-on: ubuntu-latest
    needs: [linuxNode16, linuxNode14]
    timeout-minutes: 30 # Default is 360
    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Ensure to have complete history of commits pushed with given push operation
          # It's loose and imperfect assumption that no more than 30 commits will be pushed at once
          fetch-depth: 30
          # Tag needs to be pushed with real user token, otherwise pushed tag won't trigger the actions workflow
          # Hence we're passing 'serverless-ci' user authentication token
          token: ${{ secrets.USER_GITHUB_TOKEN }}

      - name: Retrieve ~/.npm from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**package*.json') }}

      - name: Retrieve node_modules from cache
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('package.json') }}
      - name: Retrieve packages/aws-lambda-otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/package.json') }}
      - name: Retrieve packages/aws-lambda-otel-extension/opt/otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionOptOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: packages/aws-lambda-otel-extension/opt/otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/opt/otel-extension/node-modules-v16-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('packages/aws-lambda-otel-extension/opt/otel-extension/package.json') }}

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Note: No need to install dependencies as we have retrieved cached `node_modules` for very
      #       same `package.json` as stored with previous job

      - name: Integration tests
        run: |
          cd packages/aws-lambda-otel-extension
          npm run test:integration

      - name: Tag if new version
        if: false # TODO: remove once packages/aws-lambda-otel-extension/package.json lands in master
        run: |
          NEW_VERSION=`git diff -U0 ${{ github.event.before }} packages/aws-lambda-otel-extension/package.json | grep '"version": "' | tail -n 1 | grep -oE "[0-9]+\.[0-9]+\.[0-9]+"` || :
          if [ -n "$NEW_VERSION" ];
          then
            git tag @serverless/aws-lambda-otel-extension@$NEW_VERSION
            git push --tags
          fi
