# @serverless/aws-lambda-otel-extensiom@{version} tags only
name: "Node: Publish @serverless/aws-lambda-otel-extension"

on:
  push:
    tags:
      - "@serverless/aws-lambda-otel-extension@[0-9]+.[0-9]+.[0-9]+"

jobs:
  publishNewVersion:
    name: Publish new version
    runs-on: ubuntu-latest
    env:
      # It'll work with secrets.GITHUB_TOKEN (which is provided by GitHub unconditionally)
      # Still then release author would be "github-actions". It's better if it's dedicated repo bot
      GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Retrieve ~/.npm from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-v16-${{ runner.os }}-refs/heads/main-${{ hashFiles('node/**package*.json') }}
          restore-keys: npm-v16-${{ runner.os }}-refs/heads/main-

      - name: Retrieve node_modules from cache
        id: cacheNodeModules
        uses: actions/cache@v2
        with:
          path: node/node_modules
          key: node-modules-v16-${{ runner.os }}-refs/heads/main-${{ hashFiles('node/package.json') }}
          restore-keys: node-modules-v16-${{ runner.os }}-refs/heads/main-
      - name: Retrieve packages/aws-lambda-otel-extension/node_modules from cache
        id: cacheAwsLambdaOtelExtensionNodeModules
        uses: actions/cache@v2
        with:
          path: node/packages/aws-lambda-otel-extension/node_modules
          key: packages/aws-lambda-otel-extension/node-modules-v16-${{ runner.os }}-refs/heads/main-${{ hashFiles('node/packages/aws-lambda-otel-extension/package.json') }}
          restore-keys: packages/aws-lambda-otel-extension/node-modules-v16-${{ runner.os }}-refs/heads/main-
      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Node.js and npm
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org

      - name: Install main project dependencies
        if: steps.cacheNodeModules.outputs.cache-hit != 'true'
        run: |
          cd node
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension dependencies
        if: steps.cacheAwsLambdaOtelExtensionNodeModules.outputs.cache-hit != 'true'
        run: |
          cd node/packages/aws-lambda-otel-extension
          npm update --no-save
          npm update --save-dev --no-save
      - name: Install packages/aws-lambda-otel-extension/external/otel-extension-external dependencies
        run: |
          cd node/packages/aws-lambda-otel-extension/external/otel-extension-external
          npm install
      - name: Install packages/aws-lambda-otel-extension/internal/otel-extension-internal-node dependencies
        run: |
          cd node/packages/aws-lambda-otel-extension/internal/otel-extension-internal-node
          npm install

      - name: Build distributables
        run: |
          cd node/packages/aws-lambda-otel-extension
          npm run build
          npm run build:external
          npm run build:internal

      - name: Publish new version
        # Note: Setting NODE_AUTH_TOKEN as job|workspace wide env var won't work
        #       as it appears actions/setup-node sets own value
        env:
          # serverless-main npm user auth token
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd node/packages/aws-lambda-otel-extension
          npm publish

      - name: Publish release notes
        run: |
          cd node/packages/aws-lambda-otel-extension
          TAG=${GITHUB_REF:10}
          npx github-release-from-cc-changelog $TAG

      - name: Publish layers (dev)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OPEN_DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OPEN_DEV_AWS_SECRET_ACCESS_KEY }}
        run: |
          TEMP_ARRAY=($(echo $GITHUB_REF | tr "@" "\n"))
          VERSION=${TEMP_ARRAY[@]: -1}
          cd node
          ./scripts/publish-extension-layers.js \
            --bucket-name sls-dev-layers-registry \
            --layer-basename sls-otel-extension-node \
            --version $VERSION \
            --layer-filename packages/aws-lambda-otel-extension/dist/extension.zip \
          ./scripts/publish-extension-layers.js \
            --bucket-name sls-dev-layers-registry \
            --layer-basename sls-otel-extension-external \
            --version $VERSION \
            --layer-filename packages/aws-lambda-otel-extension/dist/extension-external.zip
          ./scripts/publish-extension-layers.js \
            --bucket-name sls-dev-layers-registry \
            --layer-basename sls-otel-extension-internal-node \
            --version $VERSION \
            --layer-filename packages/aws-lambda-otel-extension/dist/extension-internal.zip

      - name: Publish layers (prod)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.OPEN_PROD_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.OPEN_PROD_AWS_SECRET_ACCESS_KEY }}
        run: |
          TEMP_ARRAY=($(echo $GITHUB_REF | tr "@" "\n"))
          VERSION=${TEMP_ARRAY[@]: -1}
          TAG=${GITHUB_REF:10}
          cd node
          ./scripts/publish-extension-layers.js \
            --bucket-name sls-layers-registry \
            --layer-basename sls-otel-extension-node \
            --version $VERSION \
            --layer-filename packages/aws-lambda-otel-extension/dist/extension.zip
            --github-tag $TAG
          ./scripts/publish-extension-layers.js \
            --bucket-name sls-layers-registry \
            --layer-basename sls-otel-extension-external \
            --version $VERSION \
            --layer-filename packages/aws-lambda-otel-extension/dist/extension-external.zip
            --github-tag $TAG
          ./scripts/publish-extension-layers.js \
            --bucket-name sls-layers-registry \
            --layer-basename sls-otel-extension-internal-node \
            --version $VERSION \
            --layer-filename packages/aws-lambda-otel-extension/dist/extension-internal.zip
            --github-tag $TAG
