name: "Python: Publish python/serverless-sdk-schema"

on:
  push:
    tags:
      - "python/serverless-sdk-schema@[0-9]+.[0-9]+.[0-9]+"

jobs:
  publishNewSdkVersion:
    name: Publish new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python and Pip
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

          # ensure project dependencies are cached
          # When using only `pyproject.toml` for dependencies, see:
          #  https://github.com/actions/setup-python/issues/529#issuecomment-1367029699
          cache: 'pip'
          cache-dependency-path: |
            **/pyproject.toml

      - name: Cache protobuf
        id: cache-protobuf
        uses: actions/cache@v3
        with:
          path:  ~/protobuf
          key: "protobuf:protoc-22.2-linux-x86_32.zip"

      - name: Install protoc compiler
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v22.2/protoc-22.2-linux-x86_32.zip
          unzip protoc-22.2-linux-x86_32.zip -d ~/protobuf

      - name: Add protobuf to PATH
        run: |
          echo ~/protobuf/bin >> $GITHUB_PATH

      - name: Publish New Version
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.PYPI_AUTH_TOKEN }}
        run: |
          cd python/packages/sdk-schema
          ./scripts/compile-protobuf.sh
          python3 -m pip install --upgrade build twine wheel
          python3 -m build --wheel --sdist .
          twine upload dist/*.tar.gz dist/*.whl
